// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// cpp_helper_from_ranks_to_integrable_values
NumericVector cpp_helper_from_ranks_to_integrable_values(NumericVector rank_interval_mult, int j_max);
RcppExport SEXP _RVCompare_cpp_helper_from_ranks_to_integrable_values(SEXP rank_interval_multSEXP, SEXP j_maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type rank_interval_mult(rank_interval_multSEXP);
    Rcpp::traits::input_parameter< int >::type j_max(j_maxSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_helper_from_ranks_to_integrable_values(rank_interval_mult, j_max));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RVCompare_cpp_helper_from_ranks_to_integrable_values", (DL_FUNC) &_RVCompare_cpp_helper_from_ranks_to_integrable_values, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_RVCompare(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
